# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Rafael Lopes"
subtitle: "NYC street photography as it finest"
author: "Rafael Lopes"
header:
 title: "Photography"
 subtitle: "by Raf"
footer:
 name: "Hey there, my name is Raf"
 bio: "Brazilian street photographer living in NYC."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/deploytoprod"
  instagram: "https://www.instagram.com/bobeirasa"
#  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/cloudlopes"
  github: "https://www.github.com/bobeirasa"
